# Generated by Django 5.0.7 on 2024-12-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=100)),
                ('companylocation', models.CharField(max_length=50)),
                ('companyabout', models.TextField()),
                ('companytype', models.CharField(choices=[('IT', 'IT Company'), ('Non IT', 'Non IT Company')], max_length=100)),
                ('companyadded_date', models.DateTimeField(auto_now=True)),
                ('companystatus', models.BooleanField(default=True)),
            ],
        ),
    ]
