# Generated by Django 5.0.7 on 2024-12-30 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.AutoField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=100)),
                ('empemail', models.CharField(max_length=50)),
                ('empaddress', models.CharField(max_length=200)),
                ('empphone', models.CharField(max_length=10)),
                ('empposition', models.CharField(choices=[('SDE I', 'SDE I'), ('SDE II', 'SDE II'), ('SDE III', 'SDE III')], max_length=50)),
                ('empcompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
